---
- name: Install common utils.
  yum: state=present name="{{ item }}"
  with_items:
    - ntp
    - ed
    - mlocate
  register: result

- name: Update db
  command: updatedb
  when: result|succeeded